# -*- coding: utf-8 -*-
"""socfacialrecogSRESHTHALAHIRI24b0614.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ebn7iHmzTrbQt4crVwkvAZEk3DxnJ0_1
"""

!pip install -q transformers datasets

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.utils import to_categorical

# 1. Load Dataset
df = pd.read_csv("fer2013.csv")

# 2. Convert pixels to arrays
width, height = 48, 48
df['pixels'] = df['pixels'].apply(lambda x: np.fromstring(x, sep=' '))

# 3. Filter out rows that don't have 2304 pixels
df = df[df['pixels'].apply(lambda x: len(x) == width * height)]

# 4. Stack and reshape
X = np.stack(df['pixels'].values)
X = X.reshape(-1, width, height, 1).astype('float32') / 255.0
y = to_categorical(df['emotion'], num_classes=7)

# 2. Split
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# 3. Data Augmentation
datagen = ImageDataGenerator(
    rotation_range=20,
    zoom_range=0.2,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True
)
datagen.fit(X_train)

# 4. Build Custom CNN
model = Sequential([
    Conv2D(64, (3,3), activation='relu', padding='same', input_shape=(48,48,1)),
    BatchNormalization(),
    MaxPooling2D(2,2),

    Conv2D(128, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling2D(2,2),

    Conv2D(256, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(7, activation='softmax')
])

# 5. Compile
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# 6. Train
history = model.fit(datagen.flow(X_train, y_train, batch_size=64),
                    validation_data=(X_val, y_val),
                    epochs=30)

# 7. Plot Accuracy
plt.plot(history.history['accuracy'], label='Train Acc')
plt.plot(history.history['val_accuracy'], label='Val Acc')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()